"""AddpaymentMethod to orders

Revision ID: 1bd3a0b8c8b6
Revises: 
Create Date: 2024-12-18 09:22:34.587312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bd3a0b8c8b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paymentMethod', sa.String(length=50), nullable=False, server_default='匯款'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('pid', sa.INTEGER(), server_default=sa.text("nextval('product_pid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('ptid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_cn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('specialPrice', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remain', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productImageUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ptid'], ['product_tag.ptid'], name='product_ptid_fkey'),
    sa.PrimaryKeyConstraint('pid', name='product_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_product_title_cn', 'product', ['title_cn'], unique=False)
    op.create_index('ix_product_pid', 'product', ['pid'], unique=False)
    op.create_table('external_link',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('iconImageUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('show', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('externalLink', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='external_link_pkey')
    )
    op.create_index('ix_external_link_name_cn', 'external_link', ['name_cn'], unique=False)
    op.create_index('ix_external_link_id', 'external_link', ['id'], unique=False)
    op.create_table('about',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_cn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aboutImageUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='about_pkey')
    )
    op.create_index('ix_about_title_cn', 'about', ['title_cn'], unique=False)
    op.create_index('ix_about_id', 'about', ['id'], unique=False)
    op.create_table('terms',
    sa.Column('tid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tid', name='terms_pkey')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('teamImageUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='team_pkey')
    )
    op.create_index('ix_team_name_cn', 'team', ['name_cn'], unique=False)
    op.create_index('ix_team_id', 'team', ['id'], unique=False)
    op.create_table('order_details',
    sa.Column('odid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['oid'], ['orders.oid'], name='order_details_oid_fkey'),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='order_details_pid_fkey'),
    sa.PrimaryKeyConstraint('odid', name='order_details_pkey')
    )
    op.create_table('users',
    sa.Column('uid', sa.INTEGER(), server_default=sa.text("nextval('users_uid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('star', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('identity', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('orders',
    sa.Column('oid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalAmount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipientName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipientPhone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('recipientEmail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('orderNote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transportationMethod', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('discountPrice', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('useDiscount', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='orders_uid_fkey'),
    sa.PrimaryKeyConstraint('oid', name='orders_pkey')
    )
    op.create_table('product_tag',
    sa.Column('ptid', sa.INTEGER(), server_default=sa.text("nextval('product_tag_ptid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('productTag', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ptid', name='product_tag_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_product_tag_ptid', 'product_tag', ['ptid'], unique=False)
    op.create_table('carts',
    sa.Column('cart_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], name='carts_pid_fkey'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='carts_uid_fkey'),
    sa.PrimaryKeyConstraint('cart_id', name='carts_pkey')
    )
    op.create_table('banner',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_cn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('buttonText_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('buttonText_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('buttonLink', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bannerImageUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='banner_pkey')
    )
    op.create_index('ix_banner_title_cn', 'banner', ['title_cn'], unique=False)
    op.create_index('ix_banner_id', 'banner', ['id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_cn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_cn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    op.create_index('ix_contact_title_cn', 'contact', ['title_cn'], unique=False)
    op.create_index('ix_contact_id', 'contact', ['id'], unique=False)
    # ### end Alembic commands ###
