"""add store_selection table

Revision ID: 2ae56621b704
Revises: 5f000ad59fe1
Create Date: 2025-01-05 14:02:43.034423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ae56621b704'
down_revision: Union[str, None] = '5f000ad59fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_selection",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("merchant_trade_no", sa.String(length=50), nullable=False),
        sa.Column("logistics_sub_type", sa.String(length=50), nullable=False),
        sa.Column("cvs_store_id", sa.String(length=50), nullable=False),
        sa.Column("cvs_store_name", sa.String(length=255), nullable=False),
        sa.Column("cvs_address", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_trade_no"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("store_selection")
    # ### end Alembic commands ###
