"""add table

Revision ID: 2be37c58d0fc
Revises: 821c0e20a398
Create Date: 2025-01-08 14:04:25.636205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be37c58d0fc'
down_revision: Union[str, None] = '821c0e20a398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_details_oid_fkey', 'order_details', type_='foreignkey')
    op.create_foreign_key(None, 'order_details', 'orders', ['oid'], ['oid'])
    op.drop_constraint('shan_thai_token_uid_fkey', 'shan_thai_token', type_='foreignkey')
    op.create_foreign_key(None, 'shan_thai_token', 'users', ['uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shan_thai_token', type_='foreignkey')
    op.create_foreign_key('shan_thai_token_uid_fkey', 'shan_thai_token', 'users', ['uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.create_foreign_key('order_details_oid_fkey', 'order_details', 'orders', ['oid'], ['oid'], ondelete='CASCADE')
    # ### end Alembic commands ###
