"""add zipCode cloumn at order table

Revision ID: 2e780020d2d1
Revises: 597ff3ec4617
Create Date: 2025-01-09 14:13:41.415684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e780020d2d1'
down_revision: Union[str, None] = '597ff3ec4617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('zipCode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'zipCode')
    # ### end Alembic commands ###
