"""add logistics_order table

Revision ID: 5658d865d8ad
Revises: 2ae56621b704
Create Date: 2025-01-05 19:52:19.287013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5658d865d8ad'
down_revision: Union[str, None] = '2ae56621b704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'logistics_orders',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('merchant_trade_no', sa.String(length=20), sa.ForeignKey('orders.oid', ondelete='CASCADE'), nullable=False),
        sa.Column('rtn_code', sa.Integer, nullable=False),
        sa.Column('rtn_msg', sa.Text, nullable=True),
        sa.Column('allpay_logistics_id', sa.String(length=50), nullable=False),
        sa.Column('logistics_type', sa.String(length=20), nullable=True),
        sa.Column('logistics_sub_type', sa.String(length=20), nullable=True),
        sa.Column('goods_amount', sa.Integer, nullable=True),
        sa.Column('update_status_date', sa.DateTime, nullable=True),
        sa.Column('receiver_name', sa.String(length=50), nullable=True),
        sa.Column('receiver_cell_phone', sa.String(length=20), nullable=True),
        sa.Column('receiver_email', sa.String(length=100), nullable=True),
        sa.Column('receiver_address', sa.String(length=255), nullable=True),
        sa.Column('cvs_payment_no', sa.String(length=50), nullable=True),
        sa.Column('cvs_validation_no', sa.String(length=50), nullable=True),
        sa.Column('booking_note', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.drop_table('logistics_orders')
    # ### end Alembic commands ###
