"""Add payment_callbacks table and link to orders

Revision ID: 5d890d95eee5
Revises: e83728f13c7d
Create Date: 2025-01-02 19:56:36.710766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d890d95eee5'
down_revision: Union[str, None] = 'e83728f13c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payment_callbacks',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),  # 主鍵
        sa.Column('merchant_id', sa.String(length=50), nullable=False),  # 特店編號
        sa.Column('merchant_trade_no', sa.String(length=10), sa.ForeignKey("orders.oid", ondelete="CASCADE"), nullable=False),  # 特店交易編號
        sa.Column('store_id', sa.String(length=50), nullable=True),  # 特店旗下店舖代號
        sa.Column('rtn_code', sa.Integer, nullable=False),  # 交易狀態
        sa.Column('rtn_msg', sa.String(length=255), nullable=False),  # 交易訊息
        sa.Column('trade_no', sa.String(length=50), nullable=False),  # 綠界交易編號
        sa.Column('trade_amt', sa.Integer, nullable=False),  # 交易金額
        sa.Column('payment_date', sa.DateTime, nullable=True),  # 付款時間
        sa.Column('payment_type', sa.String(length=50), nullable=False),  # 付款方式
        sa.Column('payment_type_charge_fee', sa.Integer, default=0, nullable=False),  # 交易手續費
        sa.Column('platform_id', sa.String(length=50), nullable=True),  # 特約合作平台商代號
        sa.Column('trade_date', sa.DateTime, nullable=False),  # 訂單成立時間
        sa.Column('simulate_paid', sa.Integer, default=1, nullable=False),  # 是否模擬付款
        sa.Column('check_mac_value', sa.String(length=255), nullable=False),  # 檢查碼
        sa.Column('bank_code', sa.String(length=50), nullable=True),  # 繳費銀行代碼
        sa.Column('v_account', sa.String(length=50), nullable=True),  # 繳費虛擬帳號
        sa.Column('expire_date', sa.DateTime, nullable=True),  # 繳費期限
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now(), nullable=False),  # 記錄建立時間
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_callbacks')
    # ### end Alembic commands ###
