"""fixed payment_callbacks nullable

Revision ID: 5f000ad59fe1
Revises: 5d890d95eee5
Create Date: 2025-01-03 13:10:45.862919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f000ad59fe1'
down_revision: Union[str, None] = '5d890d95eee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_callbacks") as batch_op:
        batch_op.alter_column("merchant_id", nullable=True)
        batch_op.alter_column("store_id", nullable=True)
        batch_op.alter_column("rtn_code", nullable=True)
        batch_op.alter_column("rtn_msg", nullable=True)
        batch_op.alter_column("trade_amt", nullable=True)
        batch_op.alter_column("payment_date", nullable=True)
        batch_op.alter_column("payment_type", nullable=True)
        batch_op.alter_column("platform_id", nullable=True)
        batch_op.alter_column("check_mac_value", nullable=True)
        batch_op.alter_column("bank_code", nullable=True)
        batch_op.alter_column("trade_date", nullable=True)
        batch_op.alter_column("v_account", nullable=True)
        batch_op.alter_column("expire_date", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_callbacks") as batch_op:
        batch_op.alter_column("payment_date", nullable=False)
        batch_op.alter_column("trade_date", nullable=False)
        batch_op.alter_column("expire_date", nullable=False)
    # ### end Alembic commands ###
