"""Add shan_thai_token table

Revision ID: 9392aeecef7d
Revises: 82be471b8306
Create Date: 2024-12-31 20:20:38.902992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb002697da3e'
down_revision: Union[str, None] = '82be471b8306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shan_thai_token',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('uid', sa.Integer, sa.ForeignKey('users.uid', ondelete='CASCADE'), nullable=False),
        sa.Column('balance', sa.Integer, nullable=False, server_default="0"),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shan_thai_token')
    # ### end Alembic commands ###
