"""Add paymentMethod to orders

Revision ID: b943461d6cd7
Revises: 2d4af5a039f5
Create Date: 2024-12-18 09:11:35.335984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b943461d6cd7'
down_revision: Union[str, None] = '2d4af5a039f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paymentMethod', sa.String(length=50), nullable=False, server_default='匯款'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paymentMethod')
    # ### end Alembic commands ###
