"""Add order details table

Revision ID: d1b9c07ba2fc
Revises: dfdcd0cf8e57
Create Date: 2024-12-08 13:44:13.465064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b9c07ba2fc'
down_revision: Union[str, None] = 'dfdcd0cf8e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_pid_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'pid')
    op.drop_column('orders', 'productNumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('productNumber', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_pid_fkey', 'orders', 'product', ['pid'], ['pid'])
    # ### end Alembic commands ###
