"""Add totalAmount column to orders

Revision ID: dfdcd0cf8e57
Revises: f98d2fb06c05
Create Date: 2024-11-29 20:27:35.044405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdcd0cf8e57'
down_revision: Union[str, None] = 'f98d2fb06c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('totalAmount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'totalAmount')
    # ### end Alembic commands ###
