"""Change oid to String with length 10

Revision ID: e83728f13c7d
Revises: eb002697da3e
Create Date: 2025-01-02 19:25:50.379945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e83728f13c7d"
down_revision: Union[str, None] = "eb002697da3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除外鍵約束
    with op.batch_alter_table("order_details", schema=None) as batch_op:
        batch_op.drop_constraint("order_details_oid_fkey", type_="foreignkey")

    # 修改 oid 欄位為 String(10)
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "oid",
            existing_type=sa.Integer(),
            type_=sa.String(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("order_details", schema=None) as batch_op:
        batch_op.alter_column(
            "oid",
            existing_type=sa.Integer(),
            type_=sa.String(length=10),
            existing_nullable=False,
        )

    # 重新添加外鍵約束
    with op.batch_alter_table("order_details", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "order_details_oid_fkey", "orders", ["oid"], ["oid"], ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除外鍵約束
    with op.batch_alter_table("order_details", schema=None) as batch_op:
        batch_op.drop_constraint("order_details_oid_fkey", type_="foreignkey")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "oid",
            existing_type=sa.String(length=10),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("order_details", schema=None) as batch_op:
        batch_op.alter_column(
            "oid",
            existing_type=sa.String(length=10),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
        )

        # 重新添加外鍵約束
    with op.batch_alter_table("order_details", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "order_details_oid_fkey", "orders", ["oid"], ["oid"], ondelete="CASCADE"
        )
    # ### end Alembic commands ###
