"""Initialize database

Revision ID: f98d2fb06c05
Revises: f2bd0aa96f59
Create Date: 2024-11-27 13:51:34.002655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from modules.dbInit import Base, engine


# revision identifiers, used by Alembic.
revision: str = 'f98d2fb06c05'
down_revision: Union[str, None] = 'f2bd0aa96f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with engine.begin() as connection:
        Base.metadata.create_all(bind=connection)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with engine.begin() as connection:
        Base.metadata.drop_all(bind=connection)
    # ### end Alembic commands ###
