"""update 2025-01-11

Revision ID: 43ff5e42e164
Revises: 2ae56621b704
Create Date: 2025-01-11 19:16:09.751487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43ff5e42e164'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logistics_orders', 'rtn_msg',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('order_details_oid_fkey', 'order_details', type_='foreignkey')
    op.create_foreign_key(None, 'order_details', 'orders', ['oid'], ['oid'])
    op.add_column('orders', sa.Column('zipCode', sa.String(length=10), nullable=True))
    op.alter_column('payment_callbacks', 'payment_type_charge_fee',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_callbacks', 'simulate_paid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_callbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('shan_thai_token_uid_fkey', 'shan_thai_token', type_='foreignkey')
    op.create_foreign_key(None, 'shan_thai_token', 'users', ['uid'], ['uid'])
    op.alter_column('user_referrals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_referrals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'shan_thai_token', type_='foreignkey')
    op.create_foreign_key('shan_thai_token_uid_fkey', 'shan_thai_token', 'users', ['uid'], ['uid'], ondelete='CASCADE')
    op.alter_column('payment_callbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_callbacks', 'simulate_paid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_callbacks', 'payment_type_charge_fee',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'zipCode')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.create_foreign_key('order_details_oid_fkey', 'order_details', 'orders', ['oid'], ['oid'], ondelete='CASCADE')
    op.alter_column('logistics_orders', 'rtn_msg',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
