"""2025-01-12

Revision ID: 68f156109600
Revises: 
Create Date: 2025-01-12 10:31:52.063347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f156109600'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_details_oid_fkey', 'order_details', type_='foreignkey')

    op.alter_column('order_details', 'oid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('orders', sa.Column('zipCode', sa.String(length=10), nullable=True))
    op.alter_column('orders', 'oid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    
    op.create_foreign_key(
        'order_details_oid_fkey',
        'order_details',
        'orders',
        ['oid'],
        ['oid'],
        ondelete='CASCADE',
    )
    
    op.add_column('users', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    
    op.create_table('store_selection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_trade_no', sa.String(length=50), nullable=False),
    sa.Column('logistics_sub_type', sa.String(length=50), nullable=False),
    sa.Column('cvs_store_id', sa.String(length=50), nullable=False),
    sa.Column('cvs_store_name', sa.String(length=255), nullable=False),
    sa.Column('cvs_address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_trade_no')
    )
    op.create_table('shan_thai_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_uid', sa.Integer(), nullable=False),
    sa.Column('referred_uid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistics_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_trade_no', sa.String(length=20), nullable=False),
    sa.Column('rtn_code', sa.Integer(), nullable=False),
    sa.Column('rtn_msg', sa.Text(), nullable=True),
    sa.Column('allpay_logistics_id', sa.String(length=50), nullable=False),
    sa.Column('logistics_type', sa.String(length=20), nullable=True),
    sa.Column('logistics_sub_type', sa.String(length=20), nullable=True),
    sa.Column('goods_amount', sa.Integer(), nullable=True),
    sa.Column('update_status_date', sa.DateTime(), nullable=True),
    sa.Column('receiver_name', sa.String(length=50), nullable=True),
    sa.Column('receiver_cell_phone', sa.String(length=20), nullable=True),
    sa.Column('receiver_email', sa.String(length=100), nullable=True),
    sa.Column('receiver_address', sa.String(length=255), nullable=True),
    sa.Column('cvs_payment_no', sa.String(length=50), nullable=True),
    sa.Column('cvs_validation_no', sa.String(length=50), nullable=True),
    sa.Column('booking_note', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_trade_no'], ['orders.oid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_callbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.Column('merchant_trade_no', sa.String(length=10), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=True),
    sa.Column('rtn_code', sa.Integer(), nullable=True),
    sa.Column('rtn_msg', sa.String(length=255), nullable=True),
    sa.Column('trade_no', sa.String(length=50), nullable=False),
    sa.Column('trade_amt', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('payment_type_charge_fee', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.String(length=50), nullable=True),
    sa.Column('trade_date', sa.DateTime(), nullable=True),
    sa.Column('simulate_paid', sa.Integer(), nullable=True),
    sa.Column('check_mac_value', sa.String(length=255), nullable=True),
    sa.Column('bank_code', sa.String(length=50), nullable=True),
    sa.Column('v_account', sa.String(length=50), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_trade_no'], ['orders.oid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'referral_code')
    op.alter_column('orders', 'oid',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'zipCode')
    op.alter_column('order_details', 'oid',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('payment_callbacks')
    op.drop_table('logistics_orders')
    op.drop_table('user_referrals')
    op.drop_table('shan_thai_token')
    op.drop_table('store_selection')
    # ### end Alembic commands ###
