"""2025-01-11

Revision ID: 965eb86da329
Revises: 2be37c58d0fc
Create Date: 2025-01-11 19:29:41.700458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965eb86da329'
down_revision: Union[str, None] = '2be37c58d0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('zipCode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'zipCode')
    # ### end Alembic commands ###
